/*
 * OpenAPI Template
 *
 * A template OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// The error code.
    #[serde(rename = "code")]
    pub code: i32,
    /// A human-readable error message.
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(code: i32, message: String) -> Error {
        Error {
            code,
            message,
        }
    }
}

