/*
 * OpenAPI Template
 *
 * A template OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemInput {
    /// The name of the item.
    #[serde(rename = "name")]
    pub name: String,
    /// An optional description of the item.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ItemInput {
    pub fn new(name: String) -> ItemInput {
        ItemInput {
            name,
            description: None,
        }
    }
}

