/*
 * OpenAPI Template
 *
 * A template OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Item {
    /// The unique identifier of the item.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the item.
    #[serde(rename = "name")]
    pub name: String,
    /// An optional description of the item.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The timestamp when the item was created.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Item {
    pub fn new(id: String, name: String) -> Item {
        Item {
            id,
            name,
            description: None,
            created_at: None,
        }
    }
}

