/*
 * OpenAPI Template
 *
 * A template OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemList {
    /// The list of items.
    #[serde(rename = "items")]
    pub items: Vec<models::Item>,
    /// The total number of items available.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl ItemList {
    pub fn new(items: Vec<models::Item>) -> ItemList {
        ItemList {
            items,
            total: None,
        }
    }
}

