=begin
#OpenAPI Template

#A template OpenAPI specification.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Error
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Error do
  #let(:instance) { OpenapiClient::Error.new }

  describe 'test an instance of Error' do
    it 'should create an instance of Error' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::Error)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
