# coding: utf-8

"""
    OpenAPI Template

    A template OpenAPI specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_input import ItemInput

class TestItemInput(unittest.TestCase):
    """ItemInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemInput:
        """Test ItemInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemInput`
        """
        model = ItemInput()
        if include_optional:
            return ItemInput(
                name = 'New Item',
                description = 'This is a new item.'
            )
        else:
            return ItemInput(
                name = 'New Item',
        )
        """

    def testItemInput(self):
        """Test ItemInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
