# coding: utf-8

"""
    OpenAPI Template

    A template OpenAPI specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_create_item(self) -> None:
        """Test case for create_item

        Create an item
        """
        pass

    def test_delete_item(self) -> None:
        """Test case for delete_item

        Delete an item
        """
        pass

    def test_get_item(self) -> None:
        """Test case for get_item

        Get an item
        """
        pass

    def test_list_items(self) -> None:
        """Test case for list_items

        List all items
        """
        pass


if __name__ == '__main__':
    unittest.main()
