# coding: utf-8

"""
    OpenAPI Template

    A template OpenAPI specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_list import ItemList

class TestItemList(unittest.TestCase):
    """ItemList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemList:
        """Test ItemList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemList`
        """
        model = ItemList()
        if include_optional:
            return ItemList(
                items = [
                    openapi_client.models.item.Item(
                        id = 'abc123', 
                        name = 'Sample Item', 
                        description = 'This is a sample item.', 
                        created_at = '2024-01-01T00:00Z', )
                    ],
                total = 42
            )
        else:
            return ItemList(
                items = [
                    openapi_client.models.item.Item(
                        id = 'abc123', 
                        name = 'Sample Item', 
                        description = 'This is a sample item.', 
                        created_at = '2024-01-01T00:00Z', )
                    ],
        )
        """

    def testItemList(self):
        """Test ItemList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
