/*
OpenAPI Template

A template OpenAPI specification.

API version: 1.0.0
Contact: support@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ItemInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemInput{}

// ItemInput struct for ItemInput
type ItemInput struct {
	// The name of the item.
	Name string `json:"name"`
	// An optional description of the item.
	Description *string `json:"description,omitempty"`
}

type _ItemInput ItemInput

// NewItemInput instantiates a new ItemInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemInput(name string) *ItemInput {
	this := ItemInput{}
	this.Name = name
	return &this
}

// NewItemInputWithDefaults instantiates a new ItemInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemInputWithDefaults() *ItemInput {
	this := ItemInput{}
	return &this
}

// GetName returns the Name field value
func (o *ItemInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ItemInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ItemInput) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ItemInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ItemInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ItemInput) SetDescription(v string) {
	o.Description = &v
}

func (o ItemInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *ItemInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemInput := _ItemInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItemInput)

	if err != nil {
		return err
	}

	*o = ItemInput(varItemInput)

	return err
}

type NullableItemInput struct {
	value *ItemInput
	isSet bool
}

func (v NullableItemInput) Get() *ItemInput {
	return v.value
}

func (v *NullableItemInput) Set(val *ItemInput) {
	v.value = val
	v.isSet = true
}

func (v NullableItemInput) IsSet() bool {
	return v.isSet
}

func (v *NullableItemInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemInput(val *ItemInput) *NullableItemInput {
	return &NullableItemInput{value: val, isSet: true}
}

func (v NullableItemInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


