/*
 * OpenAPI Template
 * A template OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Item;
import org.openapitools.client.model.ItemInput;
import org.openapitools.client.model.ItemList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
@Disabled
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    /**
     * Create an item
     *
     * Creates a new item.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createItemTest() throws ApiException {
        ItemInput itemInput = null;
        Item response = api.createItem(itemInput);
        // TODO: test validations
    }

    /**
     * Delete an item
     *
     * Deletes a single item by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteItemTest() throws ApiException {
        String itemId = null;
        api.deleteItem(itemId);
        // TODO: test validations
    }

    /**
     * Get an item
     *
     * Returns a single item by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getItemTest() throws ApiException {
        String itemId = null;
        Item response = api.getItem(itemId);
        // TODO: test validations
    }

    /**
     * List all items
     *
     * Returns a paginated list of all items.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listItemsTest() throws ApiException {
        Integer limit = null;
        ItemList response = api.listItems(limit);
        // TODO: test validations
    }

}
