=begin
#OpenAPI Template

#A template OpenAPI specification.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ItemsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ItemsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ItemsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ItemsApi' do
    it 'should create an instance of ItemsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ItemsApi)
    end
  end

  # unit tests for create_item
  # Create an item
  # Creates a new item.
  # @param item_input 
  # @param [Hash] opts the optional parameters
  # @return [Item]
  describe 'create_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_item
  # Delete an item
  # Deletes a single item by its ID.
  # @param item_id The unique identifier of the item.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item
  # Get an item
  # Returns a single item by its ID.
  # @param item_id The unique identifier of the item.
  # @param [Hash] opts the optional parameters
  # @return [Item]
  describe 'get_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_items
  # List all items
  # Returns a paginated list of all items.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of items to return.
  # @return [ItemList]
  describe 'list_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
