# coding: utf-8

# flake8: noqa
"""
    OpenAPI Template

    A template OpenAPI specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.error import Error
from openapi_client.models.item import Item
from openapi_client.models.item_input import ItemInput
from openapi_client.models.item_list import ItemList

